# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
notifications:
  email: false
before_install:
  - sudo apt-get update
  - sudo apt-get -y install samtools
  - julia -e 'using Pkg; Pkg.add(https://github.com/timholy/QuadDIRECT.jl)'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --color=yes --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - travis_wait julia --color=yes --project=docs docs/make.jl
      after_success: skip
after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("InformMe")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
