# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 1.3

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get -y install samtools
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/timholy/QuadDIRECT.jl"))'

branches:
  only:
    - master
    - /^release-.*/
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

stages:
  - name: test
  - name: docs
    # build docs on master and for tags
    if: (branch = master AND type = push) OR tag IS present


script:
  - julia --project --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/timholy/QuadDIRECT.jl")); using QuadDIRECT; Pkg.test("InformMe"; coverage=true)'

jobs:
  include:
    - stage: docs
      julia: 1.3
      os: linux
      script:
        - julia --color=yes --project=docs -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/timholy/QuadDIRECT.jl")); using QuadDIRECT; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - travis_wait julia --color=yes --project=docs docs/make.jl
      after_success: skip
    - stage: test
      julia: 1.3
      os: linux
      script:
        - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/timholy/QuadDIRECT.jl")); using QuadDIRECT; Pkg.test("InformMe"; coverage=true)'
      after_success: skip

after_success: 
 - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; using InformMe; cd(dirname(dirname(pathof(InformMe)))); Codecov.submit(process_folder())'
 - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
