# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
notifications:
  email: false
before_install:
  - sudo apt-get update
  - sudo apt-get -y install samtools
codecov: true
jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      # disable global before_script in order not to install Compose twice
      before_script:
      script:
        - julia --color=yes --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - travis_wait julia --color=yes --project=docs docs/make.jl
      after_success: skip
