# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
notifications:
  email: false
before_install:
  - sudo apt-get update
  - sudo apt-get -y install samtools
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/timholy/QuadDIRECT.jl"))'
codecov: true
coveralls: true
jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --color=yes --project=docs -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/timholy/QuadDIRECT.jl")); using QuadDIRECT; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - travis_wait julia --color=yes --project=docs docs/make.jl
      after_success: skip
    - stage: "Test"
      julia: 1.3
      os: linux
      script:
        - julia --project --check-bounds=yes -e 'import Pkg; Pkg.add(PackageSpec(url="https://github.com/timholy/QuadDIRECT.jl")); using QuadDIRECT; Pkg.test("InformMe"; coverage=true)'
      after_success: 
        - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; using InformMe; cd(dirname(dirname(pathof(InformMe)))); Codecov.submit(process_folder())'
        - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
