name = "InformMe"
uuid = "6411b294-eed1-4d14-9067-456c77403b55"
authors = ["GarrettJenkinson"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
