site_name:        InformMe.jl
repo_url:         https://github.com/GarrettJenkinson/InformMe.jl
site_description: A julia package for information-theoretic modeling of WGBS methylation data.
site_author:      GarrettJenkinson

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
